#Setup
title: Marnie Woodmeade
description: Social Policy student at the University of Bristol.
profilepic: /assets/img/profilepic.jpg

# URL settings
baseurl: ""
url: "https://marniewoodmeade.co.uk"
permalink: /portfolio/:title

# Build settings
markdown: kramdown
plugins:
  - jekyll-redirect-from
exclude:
  - README.md
