#Setup
title: Marnie Woodmeade
description: Social Policy student at the University of Bristol.
profilepic: /assets/img/profilepic.jpg

# URL settings
baseurl: "/marniewoodmeade"
url: "https://lukestorry.co.uk"
permalink: /portfolio/:title

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from

exclude:
  - README.md
