#Setup
title: Marnie Woodmeade
tagline: Social Policy student at the University of Bristol.
profilepic: /assets/img/profilepic.jpg

permalink: /portfolio/:title
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
